fastlane_version "1.105.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    increment_build_number(
      build_number: ENV["TRAVIS_BUILD_NUMBER"]
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "FizzBuzz",
      clean: true,
      code_coverage: true,
      sdk: "iphonesimulator",
      devices: ["iPhone 6", "iPhone 7"]
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      readonly: true,
      type: "adhoc"
    )
    gym(
      scheme: "FizzBuzz",
      sdk: "iphoneos10.0",
      clean: true,
      include_bitcode: true,
      export_method: "ad-hoc"
      ) 
    crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      notes: 'Distributed with fastlane'
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    snapshot
    gym(scheme: "FizzBuzz")
    deliver(force: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end
end